version: '3'
services:
  infrastructure:
    image: mcr.microsoft.com/mssql/server
    container_name: microservice-demo-database
    restart: always
    environment:
      SA_PASSWORD: secret_12345
      ACCEPT_EULA: Y
      MSSQL_PID: Enterprise
    ports:
      - 1433:1433
  rabbitmq:
    image: rabbitmq:3-management
    container_name: microservice-demo-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  api:
    build: .
    container_name: microservice-demo-api
    restart: always
    depends_on:
      - infrastructure
      - rabbitmq
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
