version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: microservice-demo-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  api:
    image: microservice-demo:latest
    build: .
    container_name: microservice-demo-api
    restart: always
    depends_on:
      - infrastructure
      - rabbitmq
    ports:
      - 5000:80
      - 5001:443
